Progress bar
pharo-graphics/Toplo pull request #160
Opened 2024-06-18 11:40 UTC by LouisePla

2024-06-19 06:42 UTC, plantec commented
super, I will check it soon

2024-07-18 20:25 UTC, labordep commented
@plantec have you check?

2024-08-22 10:15 UTC, Ducasse commented
What is the status of this PR?

2024-09-25 22:12 UTC, labordep commented
I don't know :-(

2024-11-12 22:39 UTC, tinchodias commented
For circle, it looks okay:

<img width="225" alt="Screenshot 2024-11-12 at 19 38 18" src="https://github.com/user-attachments/assets/1000d4f8-feb4-4e5a-8965-ac30bf25f09a">

but for the bar, I think something is missing:

<img width="342" alt="Screenshot 2024-11-12 at 19 39 22" src="https://github.com/user-attachments/assets/aced07df-2387-42d5-a0ce-3e1bfe0d6fec">

2024-12-19 21:12 UTC, tinchodias requested changes
I have these observations:
- bar and circle have a label, but I didn't see any text when I took screenshots
- bar doesn't show the progress, only the icon

2024-12-19 21:12 UTC, tinchodias commented
@LouisePla @labordep

2025-01-10 08:00 UTC, Ducasse commented
I merged and we will see later

2025-01-10 08:00 UTC, merged

2025-01-10 08:33 UTC, labordep commented
Thanks!